# Generated by Django 5.0.3 on 2024-05-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_profile_name_profile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('excel', models.FileField(blank=True, null=True, upload_to='excel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='graphs')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='reports')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
